In [1]:
import numpy as np
x=[215,325,185,332,406,522,472,614,544,421,445,408]
y=[14.2,16.4,19.9,15.2,18.5,22.1,19.4,25.1,23.4,18.1,22.6,17.2]
matrix=np.corrcoef(x,y)
print(matrix)

[[1.         0.75161289]
 [0.75161289 1.        ]]


In [2]:
import numpy as np
x=[43,21,25,42,57,59]
y=[99,63,79,75,87,81]
matrix=np.corrcoef(x,y)
print(matrix)

[[1.         0.54712073]
 [0.54712073 1.        ]]


In [3]:
import numpy as np
D=[2,4,6,8,10]
E=[4,8,12,16,20]
matrix=np.corrcoef(D,E)
print(matrix)

[[1. 1.]
 [1. 1.]]


In [8]:
import pandas as pd
data= {
      'x' :[45,37,42,35,39],
      'y' :[38,20,30,12,22],
      'z' :[30,40,35,14,29]
      }
dataframe=pd.DataFrame(data,columns=['x','y','z'])
print("DataFrame is :")
matrix=dataframe.corr()
print("correlation matrix is :")
print(matrix)      

DataFrame is :
correlation matrix is :
          x         y         z
x  1.000000  0.992154  0.387848
y  0.992154  1.000000  0.476121
z  0.387848  0.476121  1.000000


In [ ]:
import pandas as pd
dataframe=pd.read_csv("/content/sample_data/california_housing_train.csv")
print(dataframe)
matrix=dataframe.corr()
print("correlation matrix is ")
print(matrix)

In [10]:
#MOney and hours
import numpy as np
M=[500,1500,1000,2000]
N=[5,15,10,20]
matrix=np.corrcoef(M,N)
print(matrix)

[[1. 1.]
 [1. 1.]]


In [11]:
#time during go to college from room
import numpy as np
D=[10,40,30,50,20]
T=[1,2.5,2,3,1.5]
matrix=np.corrcoef(D,T)
print(matrix)

[[1. 1.]
 [1. 1.]]


In [13]:
#body fat and age 
import numpy as np
fat=[40,80,20,50]
age=[16,50,14,70]
matrix=np.corrcoef(fat,age)
print(matrix)

[[1.         0.63373694]
 [0.63373694 1.        ]]
